#!/bin/bash
echo 'input file name'
read filename
echo '#!/bin/bash' > ${filename}
echo 'wrait the command'
read command
echo ${command} >> ${filename}
chmod +x ${filename}
./${filename}
echo 'enter your commit to up to githup'
read commit
git add . 
git commit -m ${commit}
git push
